### ISSUE TITLE
showing number of reads supporting each allele

### ISSUE THREAD

**Issue by vsvinti** [stevekm/IGV-snapshot-automator#10]
Hi there
I want to use your tool to draw diagrams for a list of variants (one each), which I am supplying in a bed file. Is it possible to tweak your script / batch script to get the snapshots to show the number of reads carrying each allele at the specified position? I can get this in IGV when I hover over the coverage for that site .. 
I would appreciate any ideas you might have, thanks!

**Comment by stevekm** [comment]
There are a number of 'extras' that are available when you use IGV interactively, such as the information in the tooltip that appears when you hover over a site or read. 

Unfortunately I do not know of any way to make this information available, since this tool is limited only to the functionalities that are included in the IGV Batchscript implementation. I don't think this is one of them. I would probably end up building my own visualization methods in that case, or look for other genome browsers to use.
