### ISSUE TITLE
Different outputs

### ISSUE THREAD

**Issue by maktolun** [stevekm/IGV-snapshot-automator#12]
Hi,

I use the IGV-snapshot-automator with "xvfb-run" command like this;

`xvfb-run java -jar bin/IGV_2.3.81/igv.jar -b IGV_Snapshots/IGV_snapshots.bat`

However, I get different output PNGs whenever I run the command with the same .bat file. Any idea? Thanks.

**Comment by stevekm** [comment]
What is different about the output? If you are loading .bam files with high coverage, then IGV will usually randomly down-sample the .bam for display. So, not all of the reads will be shown in the image, and the ones that are shown will be randomly selected. This could cause your output to look slightly different each time. This is also caused by IGV itself, not by xvfb or any part of the script. 

Let me know if its something else that is causing the discrepancy.

**Comment by maktolun** [comment]
Yes, it was an IGV down-sampling issue as you said. Thank you for your comment.
